URL_SERVICE = "https://cnt-38c6718a-111b-43e7-bb5e-5ba38ea5bcde.containerhub.tripleten-services.com"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits"
CREATE_USER_PATH = "/api/v1/users/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"