URL_SERVICE = "https://cnt-759c590e-bbc5-47b4-b238-eea7620b24db.containerhub.tripleten-services.com"
CREATE_USER_PATH = "/api/v1/users/"
KITS_PATH = "/api/v1/kits"
CREATE_USER_PATH = "/api/v1/users/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"